### PR TITLE
add/improve help text for commands

### LINKED ISSUE #123: use custom help template
I'm sure that this isn't at all a problem, but after seeing the help text over and over I can't help but feel that it could be simplified a little bit. For example, removing the 
```
VERSION:
   0.1.0
```
bit, since we have commands/flags to check the version.

### LINKED ISSUE #124: update help text for individual commands
there have been a lot of changes since the last batch of helptext updates. as core development of the CLI slows down for 2.0 support, we'll need to update to make sure the help text is complete and actually helpful for all commands. for example
```
➜ ./build/synse scan --help
NAME:
   synse scan - Enumerate all devices on the active host

USAGE:
   synse scan [command options] [arguments...]

CATEGORY:
   Synse Server Actions

DESCRIPTION:
   The scan command hits the active Synse Server host's '/scan'
   endpoint, which enumerates all devices that are known to Synse
   Server via the instance's configured plugins.

OPTIONS:
   --filter value, -f value  set filters for the output results
   --sort value              set the sort constraints for pretty output (default: "rack,board,device")
   
```

this is okay, but:
- the usage is wrong (doesn't do anything with `[arguments...]`)
- the `--filter` flag should specify that multiple filters can be used, and what the supported set of filters are
- the `--sort` flag should specify the supported fields for sorting

### LINKED ISSUE #130: Document command usage
Most command's argument stack and possibilities are completely unclear. Find a way to include this in the help text. Examples maybe?

### PR DESCRIPTION
**Pull request by edaniszewski**
This PR adds a bunch of documentation in the form of command help text. It also makes all commands define this info via the same pattern. Finally, it adds in custom templates so that all of our help output is uniform and pretty.

fixes #130 
fixes #124 
fixes #123

### CODE REVIEW

**Comment by edaniszewski** [comment]
I agree with your nit. Figured that its better to have something rather than nothing for now. We can look into making it more dynamic in the future. (I'll open an issue for it)

**Comment by timfallmk** [comment]
FWIW I added #133 that might help

**Comment by edaniszewski** [comment]
ohhh, I thought you meant some of the stuff in the actual help text was static. did you mean that some of the command completion was static?

**Comment by timfallmk** [comment]
I meant that as well, just saying it might help bypass the underlying issue of not knowing the command structure.

**Pull request merged**
