### PR TITLE
new style output formatting for synse server commands

### PR DESCRIPTION
**Pull request by edaniszewski**
adds the new style generalized formatting to the remaining commands. 

there is still some cleanup/organization that needs to happen, but I'm planning on doing that with the generalization of sorting/filtering since it is also related to that.

with these changes we should be able to test the outputs of all the commands, so tests will need to be added/updated.

### CODE REVIEW

**Comment by timfallmk** [comment]
I'm slightly confused by your structure here. Is `formatters/server` intended to format for "server" output? I would have thought "formatting" would fall into categories along the lines of "JSON, human-readable (table-ized), unformatted, etc.".

**Comment by edaniszewski** [comment]
Yeah, I see what you're saying looking at it now. 
What I intended by the structure was for the `formatters` package to mirror the `commands` package so that the commands in `commands/server` would match up with `formatters/server`, the commands in `commands/plugin` would match up with `formatters/plugin`. 

It made sense at the time, but seems like there could be better ways. This organization was mostly done to separate similar commands, e.g. there is a `read` server command e.g. `synse read` and a `read` command for plugins e.g. `synse plugins read`.

**Comment by timfallmk** [comment]
I follow you. I'm not sure what would be more helpful here. It might be worth grouping things together across "domains" (e.g. server, plugins, etc.) so that all "read" formatting commands go together. I'm _assuming_ plugins won't be allowed to modify format outside of the normal options, so that might work, if it makes logical sense.

**Comment by edaniszewski** [comment]
Yeah, I think that would make more sense than the way its being done now. Its all dealing with the same data in one form or another, so its reasonable to format it in the same way.

**Comment by timfallmk** [comment]
Another alternative would be to have the `commands` be shells to call the "functions" stored in `/pkg/<domain>`, similarly to how `ksync` ended up. That would take a lot more reorganization though.

**Comment by edaniszewski** [comment]
@timfallmk updated things to flatten out `formatters` that are now used by both plugin and server commands. this can still be cleaned up a bit, but I plan on doing that in a separate PR

**Pull request merged**
