### PR TITLE
Change device type fan_speed to fan.

### PR DESCRIPTION
**Pull request by MatthewHink**
Corresponds to https://github.com/vapor-ware/synse-plugins-internal/pull/123

### CODE REVIEW

**Comment by timfallmk** [comment]
@MatthewHink Looks like the problem here is your PR is to master. I've changed it to `v2.0`.

**Comment by MatthewHink** [comment]
Oh $^%$ - thanks

**Comment by timfallmk** [comment]
I think 2.0 is probably ready to merge, I just wanted to test it against more actual hardware before I do.

**Comment by MatthewHink** [comment]
These changes are already in v2.0. Closing.

**Pull request closed without merging**
