### PR TITLE
V2.0

### PR DESCRIPTION
**Pull request by timfallmk**
I think we're getting close to ready to merge this into master. Leaving this here for comments and eventual merge.

### CODE REVIEW

**Comment by MatthewHink** [comment]
As far as comments, can you please crush this down to one commit?

Example:
I am a build guy. We thought this was good to go and took it, but for some reason it wasn't. I'm the build guy and want to roll it back. I want to roll back one commit.

So -1 for now.

**Comment by MatthewHink** [comment]
Rolling back 130 commits is a big FU to the build guy, and nobody cares about "I commiteh more code" crap.

**Comment by edaniszewski** [comment]
i can squash now or on merge. github has a "squash and merge" option for merge. this means that while all commits show up here, when they get merged in, they will be merged as one commit. for me this is often easier/nicer because it lets me look at individual commits if I need to when reviewing. additionally, if more changes need to happen to the PR, they can all be done without having to constantly squash things back together (which can then make it hard to re-review only those changes). 

I'm good doing it either way, but I tend to prefer using the github 'squash and merge' from a workflow perspective, but thats just me.

**Comment by MatthewHink** [comment]
It's cool as long as it's one commit in the end.

**Comment by timfallmk** [comment]
@MatthewHink I'm not sure I see the problem you're referring to. It's a branch merge into `master` so there's are tags for the current head. Even if there weren't, there's no difference between `git reset HEAD` and `git reset <some commit>`. I think you may be confusing rolling back and reverting. It's actually _easier_ to remove a small thing when commits aren't squashed since you can pick which commit it came from, potentially.

I think you may be confusing `git revert` and `git reset`. The latter lets you roll back the working tree to a specific point, while the former lets you undo the changes made in the referenced commit (or group of commits). Furthermore, all releases (including this one) will be tagged, so you could revert the entire tag if you really wanted to.

As per @edaniszewski comment, it's generally a personal preference how you like your merges. I personally prefer rebasing over squashing as it keeps the history and lets me cherry pick, but @grampelberg likes it the other way around. I'm happy to hear your concerns though if that would cause you real problems.

**Comment by timfallmk** [comment]
As another point I just remembered, the changelog and release notes are generated from the commit history, so even more reason to keep them separate.

**Comment by timfallmk** [comment]
If there are no updates, I'll merge this in a bit.

**Pull request merged**
