### PR TITLE
Quick structure switchero

### PR DESCRIPTION
**Pull request by timfallmk**
Re-org the `cmd/synse/synse.go` to `cmd/synse.go` until it makes sense to have it nested. We would want to re-nest it once we have multiple categories of commands.

Also contains a fix for a future P.R. Can be merged before that one if necessary.

### CODE REVIEW

**Comment by timfallmk** [comment]
@edaniszewski Not sure why the linter is complaining about this, but I'm a little confused if you're trying to use `c *cli.Context` here, or just overlapping variables with `c`?

**Comment by edaniszewski** [comment]
derp. just overlapping variables, my bad.

**Comment by timfallmk** [comment]
No worries, figured as much. Still not sure about the lint error though.

**Comment by timfallmk** [comment]
The answer was "Because I'm an idiot, that's why"

**Comment by timfallmk** [comment]
I'm not sure why these PR's keep closing on me…


ezgif com-video-to-gif 1

**Pull request merged**
